FROM node:latest AS prod
WORKDIR /usr/src/app

ARG API_FILENAME
ARG API_PORT

COPY package.json yarn.lock ./
COPY ./api ./

RUN yarn install --production

# EXPOSE ${API_PORT}
CMD "node ${API_FILENAME}"