services:
  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static/500.html:/usr/share/nginx/html/500.html:ro
      - ./static/login_bg.jpg:/usr/share/nginx/html/login_bg.jpg:ro
      - ./static/favicon.png:/usr/share/nginx/html/favicon.png:ro
    ports:
      - "51535:80"

  mongo:
    image: mongo:4-focal
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: dromon
    volumes:
      - ./.data/mongo_db:/data/db
      - ./.data/mongo_config:/data/configdb
      - ./api/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file: api/.env
    logging:
        options:
            max-size: 100M
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 51536:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
      ME_CONFIG_MONGODB_URL: mongodb://root:toor@mongo:27017/
    depends_on:
      - mongo
  app:
    restart: unless-stopped
    build:
      context: .
    env_file: ".env"

  api:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - API_FILENAME=index.js
        - API_PORT=80
    env_file: "api/.env"
    depends_on:
      - mongo

  oauth2_api:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - API_FILENAME=service_oauth2.js
        - API_PORT=80
    env_file: "api/.env"
    depends_on:
      - mongo

  open_api:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - API_FILENAME=service_open.js
        - API_PORT=80
    env_file: "api/.env"
    depends_on:
      - mongo
