services:
  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    networks:
      - common
    expose:
      - 8080
      - 8082
      - 8083
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    logging:
        options:
            max-size: 100M
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8085
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
      ME_CONFIG_MONGODB_URL: mongodb://root:toor@mongo:27017/
    depends_on:
      - mongo
    expose:
      - 8085

  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - mongo
    networks:
      - common
    
  api:
    restart: unless-stopped
    build:
      context: .
      args:
        - API_FILENAME=index.js
        - API_PORT=8081
      dockerfile: Dockerfile.api
    depends_on:
      - mongo
    networks:
      - common

  oauth2_api:
    restart: unless-stopped
    build:
      context: .
      args:
        - API_FILENAME=service_oauth2.js
        - API_PORT=8082
      dockerfile: Dockerfile.api
    depends_on:
      - mongo
    networks:
      - common

  open_api:
    restart: unless-stopped
    build:
      context: .
      args:
        - API_FILENAME=service_open.js
        - API_PORT=8083
      dockerfile: Dockerfile.api
    depends_on:
      - mongo
    networks:
      - common

networks:
  common:
    name: common-network